rem Release\tvxmlrcr.exe ..\mcm\kpn1.xml ..\mcm\kpn2.xml > tvxmlrcr.lst

rem copy d:\kp\source\tev\xml\debug\tvxmlrcr.exe d:\kp\source\tev\xml

rem d:\kp\source\tev\xml\debug\tvxmlrcr.exe f:\wrk\kp\source\tev\mcm\kpn1.xml f:\wrk\kp\source\tev\mcm\kpn2.xml > tvxmlrcr.lst
rem d:\kp\source\tev\xml\debug\tvxmlrcr.exe d:\kp\source\tev\mcm\mcm_out\mcm.xml d:\kp\source\tev\mcm\mcm_out\mcm1.xml > tvxmlrcr.lst
f:\kp\source\tev\xml\debug\tvxmlrcr.exe f:\kp\source\tev\mcm\mcm_out\mcmc.xml f:\wrk\kp\source\tev\mcm\mcm_out\mcm1.xml > tvxmlrcr.lst
