"Q)", "backen",      "backen",      "backe, bäckst (backst), bäckt (backt)", "backe, bäckst (backst), bäckt (backt)", 
"R)", "backen",      "backen",      "buk,  (e)st (backte)", "buk,  (e)st (backte)", 
"R)", "backen",      "backen",      "büke",        "büke",        
"R)", "backen",      "backen",      "back(e)",     "back(e)",     
"R)", "backen",      "backen",      "gebacken",    "gebacken",    
"Q)", "bedingen",    "bedingen",    "bedinge,  st,  t", "bedinge,  st,  t", 
"R)", "bedingen",    "bedingen",    "bedang (bedingte)", "bedang (bedingte)", 
"R)", "bedingen",    "bedingen",    "bedänge (bedingte)", "bedänge (bedingte)", 
"R)", "bedingen",    "bedingen",    "beding(e)",   "beding(e)",   
"R)", "bedingen",    "bedingen",    "bedungen (bedingt)", "bedungen (bedingt)", 
"Q)", "befehlen",    "befehlen",    "befehle, befiehlst, befiehlt", "befehle, befiehlst, befiehlt", 
"R)", "befehlen",    "befehlen",    "befahl",      "befahl",      
"R)", "befehlen",    "befehlen",    "beföhle (befähle)", "beföhle (befähle)", 
"R)", "befehlen",    "befehlen",    "befiehl",     "befiehl",     
"R)", "befehlen",    "befehlen",    "befohlen",    "befohlen",    
"Q)", "befleißen",   "befleißen",   "befleiße,  (es)t,  t", "befleiße,  (es)t,  t", 
"R)", "befleißen",   "befleißen",   "befliss, beflissest", "befliss, beflissest", 
"R)", "befleißen",   "befleißen",   "beflisse",    "beflisse",    
"R)", "befleißen",   "befleißen",   "befleiß(e)",  "befleiß(e)",  
"R)", "befleißen",   "befleißen",   "beflissen",   "beflissen",   
"Q)", "beginnen",    "beginnen",    "beginne,  st,  t", "beginne,  st,  t", 
"R)", "beginnen",    "beginnen",    "begann",      "begann",      
"R)", "beginnen",    "beginnen",    "begönne (begänne)", "begönne (begänne)", 
"R)", "beginnen",    "beginnen",    "beginn(e)",   "beginn(e)",   
"R)", "beginnen",    "beginnen",    "begonnen",    "begonnen",    
"Q)", "beißen",      "beißen",      "beiße,  (es)t,  t", "beiße,  (es)t,  t", 
"R)", "beißen",      "beißen",      "biss, bissest", "biss, bissest", 
"R)", "beißen",      "beißen",      "bisse",       "bisse",       
"R)", "beißen",      "beißen",      "beiß(e)",     "beiß(e)",     
"R)", "beißen",      "beißen",      "gebissen",    "gebissen",    
"Q)", "bergen",      "bergen",      "berge, birgst, birgt", "berge, birgst, birgt", 
"R)", "bergen",      "bergen",      "barg",        "barg",        
"R)", "bergen",      "bergen",      "bärge",       "bärge",       
"R)", "bergen",      "bergen",      "birg",        "birg",        
"R)", "bergen",      "bergen",      "geborgen",    "geborgen",    
"Q)", "bersten",     "bersten",     "berste, birst (berstest),", "berste, birst (berstest),", 
"R)", "bersten",     "bersten",     "barst (borst, berstete),  est", "barst (borst, berstete),  est", 
"R)", "bersten",     "bersten",     "bärste",      "bärste",      
"R)", "bersten",     "bersten",     "birst",       "birst",       
"R)", "bersten",     "bersten",     "geborsten",   "geborsten",   
"Q)", "",            "",            "birst (berstet)", "birst (berstet)", 
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"Q)", "bewegen",     "bewegen",     "bewege,  st,  t", "bewege,  st,  t", 
"R)", "bewegen",     "bewegen",     "bewog",       "bewog",       
"R)", "bewegen",     "bewegen",     "bewöge",      "bewöge",      
"R)", "bewegen",     "bewegen",     "beweg(e)",    "beweg(e)",    
"R)", "bewegen",     "bewegen",     "bewogen",     "bewogen",     
"Q)", "biegen",      "biegen",      "biege,  st,  t", "biege,  st,  t", 
"R)", "biegen",      "biegen",      "bog",         "bog",         
"R)", "biegen",      "biegen",      "böge",        "böge",        
"R)", "biegen",      "biegen",      "bieg(e)",     "bieg(e)",     
"R)", "biegen",      "biegen",      "gebogen",     "gebogen",     
"Q)", "bieten",      "bieten",      "biete,  (e)st,  et", "biete,  (e)st,  et", 
"R)", "bieten",      "bieten",      "bot,  (e)st", "bot,  (e)st", 
"R)", "bieten",      "bieten",      "böte",        "böte",        
"R)", "bieten",      "bieten",      "biet(e)",     "biet(e)",     
"R)", "bieten",      "bieten",      "geboten",     "geboten",     
"Q)", "binden",      "binden",      "binde,  est,  et", "binde,  est,  et", 
"R)", "binden",      "binden",      "band,  (e)st", "band,  (e)st", 
"R)", "binden",      "binden",      "bände",       "bände",       
"R)", "binden",      "binden",      "bind(e)",     "bind(e)",     
"R)", "binden",      "binden",      "gebunden",    "gebunden",    
"Q)", "bitten",      "bitten",      "bitte,  est,  et", "bitte,  est,  et", 
"R)", "bitten",      "bitten",      "bat,  (e)st", "bat,  (e)st", 
"R)", "bitten",      "bitten",      "bäte",        "bäte",        
"R)", "bitten",      "bitten",      "bitte",       "bitte",       
"R)", "bitten",      "bitten",      "gebeten",     "gebeten",     
"Q)", "blasen",      "blasen",      "blase, bläst, bläst", "blase, bläst, bläst", 
"R)", "blasen",      "blasen",      "blies,  est", "blies,  est", 
"R)", "blasen",      "blasen",      "bliese",      "bliese",      
"R)", "blasen",      "blasen",      "blas(e)",     "blas(e)",     
"R)", "blasen",      "blasen",      "geblasen",    "geblasen",    
"Q)", "bleiben",     "bleiben",     "bleibe,  st,  t", "bleibe,  st,  t", 
"R)", "bleiben",     "bleiben",     "blieb,  (e)st", "blieb,  (e)st", 
"R)", "bleiben",     "bleiben",     "bliebe",      "bliebe",      
"R)", "bleiben",     "bleiben",     "bleib(e)",    "bleib(e)",    
"R)", "bleiben",     "bleiben",     "geblieben",   "geblieben",   
"Q)", "bleichen^*",  "bleichen^*",  "bleiche,  st,  t", "bleiche,  st,  t", 
"R)", "bleichen^*",  "bleichen^*",  "blich",       "blich",       
"R)", "bleichen^*",  "bleichen^*",  "bliche",      "bliche",      
"R)", "bleichen^*",  "bleichen^*",  "bleich(e)",   "bleich(e)",   
"R)", "bleichen^*",  "bleichen^*",  "geblichen",   "geblichen",   
"Q)", "braten",      "braten",      "brate, brätst, brät", "brate, brätst, brät", 
"R)", "braten",      "braten",      "briet,  (e)st", "briet,  (e)st", 
"R)", "braten",      "braten",      "briete",      "briete",      
"R)", "braten",      "braten",      "brat(e)",     "brat(e)",     
"R)", "braten",      "braten",      "gebraten",    "gebraten",    
"Q)", "brechen",     "brechen",     "breche, brichst, bricht", "breche, brichst, bricht", 
"R)", "brechen",     "brechen",     "brach",       "brach",       
"R)", "brechen",     "brechen",     "bräche",      "bräche",      
"R)", "brechen",     "brechen",     "brich",       "brich",       
"R)", "brechen",     "brechen",     "gebrochen",   "gebrochen",   
"Q)", "brennen",     "brennen",     "brenne,  st,  t", "brenne,  st,  t", 
"R)", "brennen",     "brennen",     "brannte",     "brannte",     
"R)", "brennen",     "brennen",     "brennte",     "brennte",     
"R)", "brennen",     "brennen",     "brenn(e)",    "brenn(e)",    
"R)", "brennen",     "brennen",     "gebrannt",    "gebrannt",    
"Q)", "bringen",     "bringen",     "bringe,  st,  t", "bringe,  st,  t", 
"R)", "bringen",     "bringen",     "brachte",     "brachte",     
"R)", "bringen",     "bringen",     "brächte",     "brächte",     
"R)", "bringen",     "bringen",     "bring(e)",    "bring(e)",    
"R)", "bringen",     "bringen",     "gebracht",    "gebracht",    
"Q)", "denken",      "denken",      "denke,  st,  t", "denke,  st,  t", 
"R)", "denken",      "denken",      "dachte",      "dachte",      
"R)", "denken",      "denken",      "dächte",      "dächte",      
"R)", "denken",      "denken",      "denk(e)",     "denk(e)",     
"R)", "denken",      "denken",      "gedacht",     "gedacht",     
"Q)", "dingen**",    "dingen**",    "dinge,  st,  t", "dinge,  st,  t", 
"R)", "dingen**",    "dingen**",    "dang (dingte)", "dang (dingte)", 
"R)", "dingen**",    "dingen**",    "ding(e)te (dünge, dänge)", "ding(e)te (dünge, dänge)", 
"R)", "dingen**",    "dingen**",    "ding(e)",     "ding(e)",     
"R)", "dingen**",    "dingen**",    "gedungen (gedingt)", "gedungen (gedingt)", 
"Q)", "dreschen",    "dreschen",    "dresche, drischst, drischt", "dresche, drischst, drischt", 
"R)", "dreschen",    "dreschen",    "drosch,  (e)st (drasch)", "drosch,  (e)st (drasch)", 
"R)", "dreschen",    "dreschen",    "drösche",     "drösche",     
"R)", "dreschen",    "dreschen",    "drisch",      "drisch",      
"R)", "dreschen",    "dreschen",    "gedroschen",  "gedroschen",  
"Q)", "dringen",     "dringen",     "dringe,  st,  t", "dringe,  st,  t", 
"R)", "dringen",     "dringen",     "drang,  (e)st", "drang,  (e)st", 
"R)", "dringen",     "dringen",     "dränge",      "dränge",      
"R)", "dringen",     "dringen",     "dring(e)",    "dring(e)",    
"R)", "dringen",     "dringen",     "gedrungen",   "gedrungen",   
"Q)", "dünken",      "dünken",      "dünkt (deucht mich)", "dünkt (deucht mich)", 
"R)", "dünken",      "dünken",      "dünkte (deuchte)", "dünkte (deuchte)", 
"R)", "dünken",      "dünken",      "–",           "–",           
"R)", "dünken",      "dünken",      "–",           "–",           
"R)", "dünken",      "dünken",      "gedünkt (gedeucht)", "gedünkt (gedeucht)", 
"Q)", "dürfen",      "dürfen",      "darf,  st,  ; dürfen", "darf,  st,  ; dürfen", 
"R)", "dürfen",      "dürfen",      "durfte",      "durfte",      
"R)", "dürfen",      "dürfen",      "dürfte",      "dürfte",      
"R)", "dürfen",      "dürfen",      "–",           "–",           
"R)", "dürfen",      "dürfen",      "gedurft",     "gedurft",     
"Q)", "empfehlen",   "empfehlen",   "empfehle, empfiehlst,", "empfehle, empfiehlst,", 
"R)", "empfehlen",   "empfehlen",   "empfahl",     "empfahl",     
"R)", "empfehlen",   "empfehlen",   "empföhle",    "empföhle",    
"R)", "empfehlen",   "empfehlen",   "empfiehl",    "empfiehl",    
"R)", "empfehlen",   "empfehlen",   "empfohlen",   "empfohlen",   
"Q)", "",            "",            "empfiehlt",   "empfiehlt",   
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"Q)", "erbleichen",  "erbleichen",  "erbleiche,  st,  t", "erbleiche,  st,  t", 
"R)", "erbleichen",  "erbleichen",  "erbleichte (erblich)", "erbleichte (erblich)", 
"R)", "erbleichen",  "erbleichen",  "erbleichte (erbliche)", "erbleichte (erbliche)", 
"R)", "erbleichen",  "erbleichen",  "erbleich(e)", "erbleich(e)", 
"R)", "erbleichen",  "erbleichen",  "erbleicht (erblichen)", "erbleicht (erblichen)", 
"Q)", "erkiesen",    "erkiesen",    "erkiese,  (es)t,  t", "erkiese,  (es)t,  t", 
"R)", "erkiesen",    "erkiesen",    "erkor",       "erkor",       
"R)", "erkiesen",    "erkiesen",    "erköre",      "erköre",      
"R)", "erkiesen",    "erkiesen",    "erkies(e)",   "erkies(e)",   
"R)", "erkiesen",    "erkiesen",    "erkoren",     "erkoren",     
"Q)", "erlöschen",   "erlöschen",   "erlösche, erlischst, erlischt", "erlösche, erlischst, erlischt", 
"R)", "erlöschen",   "erlöschen",   "erlosch,  est", "erlosch,  est", 
"R)", "erlöschen",   "erlöschen",   "",            "",            
"R)", "erlöschen",   "erlöschen",   "",            "",            
"R)", "erlöschen",   "erlöschen",   "",            "",            
"Q)", "erschrecken", "erschrecken", "erschrecke, erschrickst, erschrickt", "erschrecke, erschrickst, erschrickt", 
"R)", "erschrecken", "erschrecken", "erschrak,  (e)st", "erschrak,  (e)st", 
"R)", "erschrecken", "erschrecken", "erschräke",   "erschräke",   
"R)", "erschrecken", "erschrecken", "erschrick",   "erschrick",   
"R)", "erschrecken", "erschrecken", "erschrocken", "erschrocken", 
"Q)", "erwägen",     "erwägen",     "erwäge,  st,  t", "erwäge,  st,  t", 
"R)", "erwägen",     "erwägen",     "erwog,  (e)st", "erwog,  (e)st", 
"R)", "erwägen",     "erwägen",     "erwöge",      "erwöge",      
"R)", "erwägen",     "erwägen",     "erwäg(e)",    "erwäg(e)",    
"R)", "erwägen",     "erwägen",     "erwogen",     "erwogen",     
"Q)", "essen",       "essen",       "esse, isst ir issest, isst", "esse, isst ir issest, isst", 
"R)", "essen",       "essen",       "aß,  est",    "aß,  est",    
"R)", "essen",       "essen",       "äße",         "äße",         
"R)", "essen",       "essen",       "iss",         "iss",         
"R)", "essen",       "essen",       "gegessen",    "gegessen",    
"Q)", "fahren",      "fahren",      "fahre, fährst fährt", "fahre, fährst fährt", 
"R)", "fahren",      "fahren",      "fuhr,  (e)st", "fuhr,  (e)st", 
"R)", "fahren",      "fahren",      "führe",       "führe",       
"R)", "fahren",      "fahren",      "fahr(e)",     "fahr(e)",     
"R)", "fahren",      "fahren",      "gefahren",    "gefahren",    
"Q)", "fallen",      "fallen",      "falle, fällst, fällt", "falle, fällst, fällt", 
"R)", "fallen",      "fallen",      "fiel",        "fiel",        
"R)", "fallen",      "fallen",      "fiele",       "fiele",       
"R)", "fallen",      "fallen",      "fall(e)",     "fall(e)",     
"R)", "fallen",      "fallen",      "gefallen",    "gefallen",    
"Q)", "fangen",      "fangen",      "fange, fängst, fängt", "fange, fängst, fängt", 
"R)", "fangen",      "fangen",      "fing",        "fing",        
"R)", "fangen",      "fangen",      "finge",       "finge",       
"R)", "fangen",      "fangen",      "fang(e)",     "fang(e)",     
"R)", "fangen",      "fangen",      "gefangen",    "gefangen",    
"Q)", "fechten",     "fechten",     "fechte, fich(t)st, ficht", "fechte, fich(t)st, ficht", 
"R)", "fechten",     "fechten",     "focht,  (e)st", "focht,  (e)st", 
"R)", "fechten",     "fechten",     "föchte",      "föchte",      
"R)", "fechten",     "fechten",     "ficht",       "ficht",       
"R)", "fechten",     "fechten",     "gefochten",   "gefochten",   
"Q)", "finden",      "finden",      "finde,  est,  et", "finde,  est,  et", 
"R)", "finden",      "finden",      "fand,  (e)st", "fand,  (e)st", 
"R)", "finden",      "finden",      "fände",       "fände",       
"R)", "finden",      "finden",      "find(e)",     "find(e)",     
"R)", "finden",      "finden",      "gefunden",    "gefunden",    
"Q)", "flechten",    "flechten",    "flechte, flich(t)st (flechtest),", "flechte, flich(t)st (flechtest),", 
"R)", "flechten",    "flechten",    "flocht,  est", "flocht,  est", 
"R)", "flechten",    "flechten",    "flöchte",     "flöchte",     
"R)", "flechten",    "flechten",    "flicht (flecht(e))", "flicht (flecht(e))", 
"R)", "flechten",    "flechten",    "geflochten",  "geflochten",  
"Q)", "",            "",            "flicht (flechtet)", "flicht (flechtet)", 
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"Q)", "fliegen",     "fliegen",     "fliege,  st,  t", "fliege,  st,  t", 
"R)", "fliegen",     "fliegen",     "flog,  (e)st", "flog,  (e)st", 
"R)", "fliegen",     "fliegen",     "flöge",       "flöge",       
"R)", "fliegen",     "fliegen",     "flieg(e)",    "flieg(e)",    
"R)", "fliegen",     "fliegen",     "geflogen",    "geflogen",    
"Q)", "fliehen",     "fliehen",     "fliehe,  st,  t", "fliehe,  st,  t", 
"R)", "fliehen",     "fliehen",     "floh,  (e)st", "floh,  (e)st", 
"R)", "fliehen",     "fliehen",     "flöhe",       "flöhe",       
"R)", "fliehen",     "fliehen",     "flieh(e)",    "flieh(e)",    
"R)", "fliehen",     "fliehen",     "geflohen",    "geflohen",    
"Q)", "fließen",     "fließen",     "fließe,  t,  t", "fließe,  t,  t", 
"R)", "fließen",     "fließen",     "floss, flossest", "floss, flossest", 
"R)", "fließen",     "fließen",     "flösse",      "flösse",      
"R)", "fließen",     "fließen",     "fließ(e)",    "fließ(e)",    
"R)", "fließen",     "fließen",     "geflossen",   "geflossen",   
"Q)", "fressen",     "fressen",     "fresse, frisst, frißt", "fresse, frisst, frißt", 
"R)", "fressen",     "fressen",     "fraß,  est",  "fraß,  est",  
"R)", "fressen",     "fressen",     "fräße",       "fräße",       
"R)", "fressen",     "fressen",     "friß",        "friß",        
"R)", "fressen",     "fressen",     "gefressen",   "gefressen",   
"Q)", "frieren",     "frieren",     "friere,  st,  t", "friere,  st,  t", 
"R)", "frieren",     "frieren",     "fror",        "fror",        
"R)", "frieren",     "frieren",     "fröre",       "fröre",       
"R)", "frieren",     "frieren",     "frier(e)",    "frier(e)",    
"R)", "frieren",     "frieren",     "gefroren",    "gefroren",    
"Q)", "gären",       "gären",       "gäre,  st,  t", "gäre,  st,  t", 
"R)", "gären",       "gären",       "gärte (gor)", "gärte (gor)", 
"R)", "gären",       "gären",       "gärte (göre)", "gärte (göre)", 
"R)", "gären",       "gären",       "gär(e)",      "gär(e)",      
"R)", "gären",       "gären",       "gegoren (gegärt)", "gegoren (gegärt)", 
"Q)", "gebären",     "gebären",     "gebäre, gebärst (gebierst),", "gebäre, gebärst (gebierst),", 
"R)", "gebären",     "gebären",     "gebar",       "gebar",       
"R)", "gebären",     "gebären",     "gebäre",      "gebäre",      
"R)", "gebären",     "gebären",     "gebär(e) (gebier)", "gebär(e) (gebier)", 
"R)", "gebären",     "gebären",     "geboren",     "geboren",     
"Q)", "",            "",            "gebärt (gebiert)", "gebärt (gebiert)", 
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"Q)", "geben",       "geben",       "gebe, gibst, gibt", "gebe, gibst, gibt", 
"R)", "geben",       "geben",       "gab",         "gab",         
"R)", "geben",       "geben",       "gäbe",        "gäbe",        
"R)", "geben",       "geben",       "gib",         "gib",         
"R)", "geben",       "geben",       "gegeben",     "gegeben",     
"Q)", "gedeihen",    "gedeihen",    "gedeihe,  st,  t", "gedeihe,  st,  t", 
"R)", "gedeihen",    "gedeihen",    "gedieh",      "gedieh",      
"R)", "gedeihen",    "gedeihen",    "gediehe",     "gediehe",     
"R)", "gedeihen",    "gedeihen",    "gedeih(e)",   "gedeih(e)",   
"R)", "gedeihen",    "gedeihen",    "gediehen",    "gediehen",    
"Q)", "geh(e)n",     "geh(e)n",     "gehe,  st,  t", "gehe,  st,  t", 
"R)", "geh(e)n",     "geh(e)n",     "ging",        "ging",        
"R)", "geh(e)n",     "geh(e)n",     "ginge",       "ginge",       
"R)", "geh(e)n",     "geh(e)n",     "geh(e)",      "geh(e)",      
"R)", "geh(e)n",     "geh(e)n",     "gegangen",    "gegangen",    
"Q)", "gelingen",    "gelingen",    "es gelingt",  "es gelingt",  
"R)", "gelingen",    "gelingen",    "es gelang",   "es gelang",   
"R)", "gelingen",    "gelingen",    "es gelänge",  "es gelänge",  
"R)", "gelingen",    "gelingen",    "geling(e)",   "geling(e)",   
"R)", "gelingen",    "gelingen",    "gelungen",    "gelungen",    
"Q)", "gelten",      "gelten",      "gelte, giltst, gilt", "gelte, giltst, gilt", 
"R)", "gelten",      "gelten",      "galt,  est",  "galt,  est",  
"R)", "gelten",      "gelten",      "gälte (gölte)", "gälte (gölte)", 
"R)", "gelten",      "gelten",      "gilt",        "gilt",        
"R)", "gelten",      "gelten",      "gegolten",    "gegolten",    
"Q)", "genesen",     "genesen",     "genese,  (es)t,  t", "genese,  (es)t,  t", 
"R)", "genesen",     "genesen",     "genas,  est", "genas,  est", 
"R)", "genesen",     "genesen",     "genäse",      "genäse",      
"R)", "genesen",     "genesen",     "genese",      "genese",      
"R)", "genesen",     "genesen",     "genesen",     "genesen",     
"Q)", "genießen",    "genießen",    "genieße,  (es)t,  t", "genieße,  (es)t,  t", 
"R)", "genießen",    "genießen",    "genoss",      "genoss",      
"R)", "genießen",    "genießen",    "genösse",     "genösse",     
"R)", "genießen",    "genießen",    "genieß(e)",   "genieß(e)",   
"R)", "genießen",    "genießen",    "genossen",    "genossen",    
"Q)", "geschehen",   "geschehen",   "es geschieht", "es geschieht", 
"R)", "geschehen",   "geschehen",   "es geschah",  "es geschah",  
"R)", "geschehen",   "geschehen",   "es geschähe", "es geschähe", 
"R)", "geschehen",   "geschehen",   "–",           "–",           
"R)", "geschehen",   "geschehen",   "geschehen",   "geschehen",   
"Q)", "gewinnen",    "gewinnen",    "gewinne,  st,  t", "gewinne,  st,  t", 
"R)", "gewinnen",    "gewinnen",    "gewann,  (e)st", "gewann,  (e)st", 
"R)", "gewinnen",    "gewinnen",    "gewänne (gewönne)", "gewänne (gewönne)", 
"R)", "gewinnen",    "gewinnen",    "gewinn(e)",   "gewinn(e)",   
"R)", "gewinnen",    "gewinnen",    "gewonnen",    "gewonnen",    
"Q)", "gießen",      "gießen",      "gieße  t,  t", "gieße  t,  t", 
"R)", "gießen",      "gießen",      "goss, gossest", "goss, gossest", 
"R)", "gießen",      "gießen",      "gösse",       "gösse",       
"R)", "gießen",      "gießen",      "gieß(e)",     "gieß(e)",     
"R)", "gießen",      "gießen",      "gegossen",    "gegossen",    
"Q)", "gleichen",    "gleichen",    "gleiche,  st,  t", "gleiche,  st,  t", 
"R)", "gleichen",    "gleichen",    "glich,  (e)st", "glich,  (e)st", 
"R)", "gleichen",    "gleichen",    "gliche",      "gliche",      
"R)", "gleichen",    "gleichen",    "gleich(e)",   "gleich(e)",   
"R)", "gleichen",    "gleichen",    "geglichen",   "geglichen",   
"Q)", "gleißen",     "gleißen",     "gleiße,  (es)t,  t", "gleiße,  (es)t,  t", 
"R)", "gleißen",     "gleißen",     "gleißte (gliss), glissest", "gleißte (gliss), glissest", 
"R)", "gleißen",     "gleißen",     "glisse",      "glisse",      
"R)", "gleißen",     "gleißen",     "gleiß(e)",    "gleiß(e)",    
"R)", "gleißen",     "gleißen",     "gegleißt (geglissen)", "gegleißt (geglissen)", 
"Q)", "gleiten",     "gleiten",     "gleite,  est,  et", "gleite,  est,  et", 
"R)", "gleiten",     "gleiten",     "glitt,  (e)st", "glitt,  (e)st", 
"R)", "gleiten",     "gleiten",     "glitte",      "glitte",      
"R)", "gleiten",     "gleiten",     "gleit(e)",    "gleit(e)",    
"R)", "gleiten",     "gleiten",     "geglitten",   "geglitten",   
"Q)", "glimmen",     "glimmen",     "glimme,  st,  t", "glimme,  st,  t", 
"R)", "glimmen",     "glimmen",     "glimmte (glomm)", "glimmte (glomm)", 
"R)", "glimmen",     "glimmen",     "glömme",      "glömme",      
"R)", "glimmen",     "glimmen",     "glimm(e)",    "glimm(e)",    
"R)", "glimmen",     "glimmen",     "geglommen (geglimmt)", "geglommen (geglimmt)", 
"Q)", "graben",      "graben",      "grabe, gräbst, gräbt", "grabe, gräbst, gräbt", 
"R)", "graben",      "graben",      "grub,  (e)st", "grub,  (e)st", 
"R)", "graben",      "graben",      "grübe",       "grübe",       
"R)", "graben",      "graben",      "grab(e)",     "grab(e)",     
"R)", "graben",      "graben",      "gegraben",    "gegraben",    
"Q)", "greifen",     "greifen",     "greife  st,  t", "greife  st,  t", 
"R)", "greifen",     "greifen",     "griff,  (e)st", "griff,  (e)st", 
"R)", "greifen",     "greifen",     "griffe",      "griffe",      
"R)", "greifen",     "greifen",     "greif(e)",    "greif(e)",    
"R)", "greifen",     "greifen",     "gegriffen",   "gegriffen",   
"Q)", "haben",       "haben",       "habe, hast, hat", "habe, hast, hat", 
"R)", "haben",       "haben",       "hatte",       "hatte",       
"R)", "haben",       "haben",       "hätte",       "hätte",       
"R)", "haben",       "haben",       "hab(e)",      "hab(e)",      
"R)", "haben",       "haben",       "gehabt",      "gehabt",      
"Q)", "halten",      "halten",      "halte, hältst, hält", "halte, hältst, hält", 
"R)", "halten",      "halten",      "hielt,  (e)st", "hielt,  (e)st", 
"R)", "halten",      "halten",      "hielte",      "hielte",      
"R)", "halten",      "halten",      "halt(e)",     "halt(e)",     
"R)", "halten",      "halten",      "gehalten",    "gehalten",    
"Q)", "hängen (hangen) vi", "hängen (hangen) vi", "hänge (hange), hängst, hängt", "hänge (hange), hängst, hängt", 
"R)", "hängen (hangen) vi", "hängen (hangen) vi", "hing,  (e)st", "hing,  (e)st", 
"R)", "hängen (hangen) vi", "hängen (hangen) vi", "hinge",       "hinge",       
"R)", "hängen (hangen) vi", "hängen (hangen) vi", "häng(e)",     "häng(e)",     
"R)", "hängen (hangen) vi", "hängen (hangen) vi", "gehangen",    "gehangen",    
"Q)", "hauen",       "hauen",       "haue,  st,  t", "haue,  st,  t", 
"R)", "hauen",       "hauen",       "haute (hieb)", "haute (hieb)", 
"R)", "hauen",       "hauen",       "hiebe (haute)", "hiebe (haute)", 
"R)", "hauen",       "hauen",       "hau(e)",      "hau(e)",      
"R)", "hauen",       "hauen",       "gehauen",     "gehauen",     
"Q)", "heben",       "heben",       "hebe,  st,  t", "hebe,  st,  t", 
"R)", "heben",       "heben",       "hob (hub),  (e)st", "hob (hub),  (e)st", 
"R)", "heben",       "heben",       "höbe (hübe)", "höbe (hübe)", 
"R)", "heben",       "heben",       "heb(e)",      "heb(e)",      
"R)", "heben",       "heben",       "gehoben",     "gehoben",     
"Q)", "heißen",      "heißen",      "heiße,  (es)t,  t", "heiße,  (es)t,  t", 
"R)", "heißen",      "heißen",      "hieß,  est",  "hieß,  est",  
"R)", "heißen",      "heißen",      "hieße",       "hieße",       
"R)", "heißen",      "heißen",      "heiß(e)",     "heiß(e)",     
"R)", "heißen",      "heißen",      "geheißen",    "geheißen",    
"Q)", "helfen",      "helfen",      "helfe, hilfst, hilft", "helfe, hilfst, hilft", 
"R)", "helfen",      "helfen",      "half,  (e)st", "half,  (e)st", 
"R)", "helfen",      "helfen",      "hülfe",       "hülfe",       
"R)", "helfen",      "helfen",      "hilf",        "hilf",        
"R)", "helfen",      "helfen",      "geholfen",    "geholfen",    
"Q)", "kennen",      "kennen",      "kenne,  st,  t", "kenne,  st,  t", 
"R)", "kennen",      "kennen",      "kannte",      "kannte",      
"R)", "kennen",      "kennen",      "kennte",      "kennte",      
"R)", "kennen",      "kennen",      "kenn(e)",     "kenn(e)",     
"R)", "kennen",      "kennen",      "gekannt",     "gekannt",     
"Q)", "klimmen",     "klimmen",     "klimme,  st,  t", "klimme,  st,  t", 
"R)", "klimmen",     "klimmen",     "klimmte (klomm)", "klimmte (klomm)", 
"R)", "klimmen",     "klimmen",     "klömme",      "klömme",      
"R)", "klimmen",     "klimmen",     "klimm(e)",    "klimm(e)",    
"R)", "klimmen",     "klimmen",     "geklommen",   "geklommen",   
"Q)", "klingen",     "klingen",     "klinge,  st,  t", "klinge,  st,  t", 
"R)", "klingen",     "klingen",     "klang,  (e)st", "klang,  (e)st", 
"R)", "klingen",     "klingen",     "klänge",      "klänge",      
"R)", "klingen",     "klingen",     "kling(e)",    "kling(e)",    
"R)", "klingen",     "klingen",     "geklungen",   "geklungen",   
"Q)", "kneifen",     "kneifen",     "kneife,  st,  t", "kneife,  st,  t", 
"R)", "kneifen",     "kneifen",     "kniff,  (e)st", "kniff,  (e)st", 
"R)", "kneifen",     "kneifen",     "kniffe",      "kniffe",      
"R)", "kneifen",     "kneifen",     "kneif(e)",    "kneif(e)",    
"R)", "kneifen",     "kneifen",     "gekniffen",   "gekniffen",   
"Q)", "kommen",      "kommen",      "komme,  st,  t", "komme,  st,  t", 
"R)", "kommen",      "kommen",      "kam",         "kam",         
"R)", "kommen",      "kommen",      "käme",        "käme",        
"R)", "kommen",      "kommen",      "komm(e)",     "komm(e)",     
"R)", "kommen",      "kommen",      "gekommen",    "gekommen",    
"Q)", "können",      "können",      "kann,  st,  ; können", "kann,  st,  ; können", 
"R)", "können",      "können",      "konnte",      "konnte",      
"R)", "können",      "können",      "könnte",      "könnte",      
"R)", "können",      "können",      "–",           "–",           
"R)", "können",      "können",      "gekonnt",     "gekonnt",     
"Q)", "kriechen",    "kriechen",    "kriech(e),  st,  t", "kriech(e),  st,  t", 
"R)", "kriechen",    "kriechen",    "kroch",       "kroch",       
"R)", "kriechen",    "kriechen",    "kröche",      "kröche",      
"R)", "kriechen",    "kriechen",    "kriech(e)",   "kriech(e)",   
"R)", "kriechen",    "kriechen",    "gekrochen",   "gekrochen",   
"Q)", "laden krauti", "laden krauti", "lade, lädst, lädt", "lade, lädst, lädt", 
"R)", "laden krauti", "laden krauti", "lud,  (e)st", "lud,  (e)st", 
"R)", "laden krauti", "laden krauti", "lüde",        "lüde",        
"R)", "laden krauti", "laden krauti", "lad(e)",      "lad(e)",      
"R)", "laden krauti", "laden krauti", "geladen",     "geladen",     
"Q)", "laden kviesti", "laden kviesti", "lade, lädst, lädt ir ladest, ladet", "lade, lädst, lädt ir ladest, ladet", 
"R)", "laden kviesti", "laden kviesti", "lud (ladete),  (e)st", "lud (ladete),  (e)st", 
"R)", "laden kviesti", "laden kviesti", "lüde (ladete)", "lüde (ladete)", 
"R)", "laden kviesti", "laden kviesti", "lad(e)",      "lad(e)",      
"R)", "laden kviesti", "laden kviesti", "geladen",     "geladen",     
"Q)", "lassen",      "lassen",      "lasse, lässt, lässt", "lasse, lässt, lässt", 
"R)", "lassen",      "lassen",      "ließ,  est",  "ließ,  est",  
"R)", "lassen",      "lassen",      "ließe",       "ließe",       
"R)", "lassen",      "lassen",      "laß (lasse)", "laß (lasse)", 
"R)", "lassen",      "lassen",      "gelassen",    "gelassen",    
"Q)", "laufen",      "laufen",      "laufe, läufst, läuft", "laufe, läufst, läuft", 
"R)", "laufen",      "laufen",      "lief,  (e)st", "lief,  (e)st", 
"R)", "laufen",      "laufen",      "liefe",       "liefe",       
"R)", "laufen",      "laufen",      "lauf(e)",     "lauf(e)",     
"R)", "laufen",      "laufen",      "gelaufen",    "gelaufen",    
"Q)", "leiden",      "leiden",      "leide,  est,  et", "leide,  est,  et", 
"R)", "leiden",      "leiden",      "litt,  (e)st", "litt,  (e)st", 
"R)", "leiden",      "leiden",      "litte",       "litte",       
"R)", "leiden",      "leiden",      "leid(e)",     "leid(e)",     
"R)", "leiden",      "leiden",      "gelitten",    "gelitten",    
"Q)", "leihen",      "leihen",      "leihe,  st,  t", "leihe,  st,  t", 
"R)", "leihen",      "leihen",      "lieh,  (e)st", "lieh,  (e)st", 
"R)", "leihen",      "leihen",      "liehe",       "liehe",       
"R)", "leihen",      "leihen",      "leih(e)",     "leih(e)",     
"R)", "leihen",      "leihen",      "geliehen",    "geliehen",    
"Q)", "lesen",       "lesen",       "lese, liest, liest", "lese, liest, liest", 
"R)", "lesen",       "lesen",       "las,  est",   "las,  est",   
"R)", "lesen",       "lesen",       "läse",        "läse",        
"R)", "lesen",       "lesen",       "lies",        "lies",        
"R)", "lesen",       "lesen",       "gelesen",     "gelesen",     
"Q)", "liegen",      "liegen",      "liege,  st,  t", "liege,  st,  t", 
"R)", "liegen",      "liegen",      "lag",         "lag",         
"R)", "liegen",      "liegen",      "läge",        "läge",        
"R)", "liegen",      "liegen",      "lieg(e)",     "lieg(e)",     
"R)", "liegen",      "liegen",      "gelegen",     "gelegen",     
"Q)", "lügen",       "lügen",       "lüge,  st,  t", "lüge,  st,  t", 
"R)", "lügen",       "lügen",       "log",         "log",         
"R)", "lügen",       "lügen",       "löge",        "löge",        
"R)", "lügen",       "lügen",       "lüg(e)",      "lüg(e)",      
"R)", "lügen",       "lügen",       "gelogen",     "gelogen",     
"Q)", "mahlen",      "mahlen",      "mahle,  st,  t", "mahle,  st,  t", 
"R)", "mahlen",      "mahlen",      "mahlte",      "mahlte",      
"R)", "mahlen",      "mahlen",      "mahlte",      "mahlte",      
"R)", "mahlen",      "mahlen",      "mahl(e)",     "mahl(e)",     
"R)", "mahlen",      "mahlen",      "gemahlen",    "gemahlen",    
"Q)", "meiden",      "meiden",      "meide,  est,  et", "meide,  est,  et", 
"R)", "meiden",      "meiden",      "mied,  (e)st", "mied,  (e)st", 
"R)", "meiden",      "meiden",      "miede",       "miede",       
"R)", "meiden",      "meiden",      "meid(e)",     "meid(e)",     
"R)", "meiden",      "meiden",      "gemieden",    "gemieden",    
"Q)", "melken",      "melken",      "melke,  st (milkst),  t (milkt)", "melke,  st (milkst),  t (milkt)", 
"R)", "melken",      "melken",      "melkte ir molk", "melkte ir molk", 
"R)", "melken",      "melken",      "mölke",       "mölke",       
"R)", "melken",      "melken",      "melk(e)",     "melk(e)",     
"R)", "melken",      "melken",      "gemelkt (gemolken)", "gemelkt (gemolken)", 
"Q)", "messen",      "messen",      "messe, misst, mißt", "messe, misst, mißt", 
"R)", "messen",      "messen",      "maß,  est",   "maß,  est",   
"R)", "messen",      "messen",      "mäße",        "mäße",        
"R)", "messen",      "messen",      "miss",        "miss",        
"R)", "messen",      "messen",      "gemessen",    "gemessen",    
"Q)", "mißlingen",   "mißlingen",   "es mißlingt", "es mißlingt", 
"R)", "mißlingen",   "mißlingen",   "es mißlang",  "es mißlang",  
"R)", "mißlingen",   "mißlingen",   "es mißlänge", "es mißlänge", 
"R)", "mißlingen",   "mißlingen",   "–",           "–",           
"R)", "mißlingen",   "mißlingen",   "mißlungen",   "mißlungen",   
"Q)", "mögen",       "mögen",       "mag,  st,  ; mögen", "mag,  st,  ; mögen", 
"R)", "mögen",       "mögen",       "mochte",      "mochte",      
"R)", "mögen",       "mögen",       "möchte",      "möchte",      
"R)", "mögen",       "mögen",       "–",           "–",           
"R)", "mögen",       "mögen",       "gemocht",     "gemocht",     
"Q)", "müssen",      "müssen",      "muss,  t,  ; müssen", "muss,  t,  ; müssen", 
"R)", "müssen",      "müssen",      "mußte",       "mußte",       
"R)", "müssen",      "müssen",      "müßte",       "müßte",       
"R)", "müssen",      "müssen",      "–",           "–",           
"R)", "müssen",      "müssen",      "gemusst",     "gemusst",     
"Q)", "nehmen",      "nehmen",      "nehme, nimmst, nimmt", "nehme, nimmst, nimmt", 
"R)", "nehmen",      "nehmen",      "nahm,  (e)st", "nahm,  (e)st", 
"R)", "nehmen",      "nehmen",      "nähme",       "nähme",       
"R)", "nehmen",      "nehmen",      "nimm",        "nimm",        
"R)", "nehmen",      "nehmen",      "genommen",    "genommen",    
"Q)", "nennen",      "nennen",      "nenne,  st,  t", "nenne,  st,  t", 
"R)", "nennen",      "nennen",      "nannte",      "nannte",      
"R)", "nennen",      "nennen",      "nennte",      "nennte",      
"R)", "nennen",      "nennen",      "nenn(e)",     "nenn(e)",     
"R)", "nennen",      "nennen",      "genannt",     "genannt",     
"Q)", "pfeifen",     "pfeifen",     "pfeife,  st,  t", "pfeife,  st,  t", 
"R)", "pfeifen",     "pfeifen",     "pfiff,  (e)st", "pfiff,  (e)st", 
"R)", "pfeifen",     "pfeifen",     "pfiffe",      "pfiffe",      
"R)", "pfeifen",     "pfeifen",     "pfeif(e)",    "pfeif(e)",    
"R)", "pfeifen",     "pfeifen",     "gepfiffen",   "gepfiffen",   
"Q)", "pflegen",     "pflegen",     "pflege,  st,  t", "pflege,  st,  t", 
"R)", "pflegen",     "pflegen",     "pflegte (pflog),  st (pflogst)", "pflegte (pflog),  st (pflogst)", 
"R)", "pflegen",     "pflegen",     "pflegte (pflöge)", "pflegte (pflöge)", 
"R)", "pflegen",     "pflegen",     "pfleg(e)",    "pfleg(e)",    
"R)", "pflegen",     "pflegen",     "gepflegt (gepflogen)", "gepflegt (gepflogen)", 
"Q)", "preisen",     "preisen",     "preise,  t,  t", "preise,  t,  t", 
"R)", "preisen",     "preisen",     "pries,  est", "pries,  est", 
"R)", "preisen",     "preisen",     "priese",      "priese",      
"R)", "preisen",     "preisen",     "preis(e)",    "preis(e)",    
"R)", "preisen",     "preisen",     "gepriesen",   "gepriesen",   
"Q)", "quellen",     "quellen",     "quelle, quillst (quellst),", "quelle, quillst (quellst),", 
"R)", "quellen",     "quellen",     "quoll (quellte)", "quoll (quellte)", 
"R)", "quellen",     "quellen",     "quölle",      "quölle",      
"R)", "quellen",     "quellen",     "quill (quelle)", "quill (quelle)", 
"R)", "quellen",     "quellen",     "gequollen (gequellt)", "gequollen (gequellt)", 
"Q)", "",            "",            "quillt (quellt)", "quillt (quellt)", 
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"R)", "",            "",            "",            "",            
"Q)", "raten",       "raten",       "rate, rätst, rät", "rate, rätst, rät", 
"R)", "raten",       "raten",       "riet,  (e)st", "riet,  (e)st", 
"R)", "raten",       "raten",       "riete",       "riete",       
"R)", "raten",       "raten",       "rat(e)",      "rat(e)",      
"R)", "raten",       "raten",       "geraten",     "geraten",     
"Q)", "reiben",      "reiben",      "reibe,  st,  t", "reibe,  st,  t", 
"R)", "reiben",      "reiben",      "rieb,  (e)st", "rieb,  (e)st", 
"R)", "reiben",      "reiben",      "riebe",       "riebe",       
"R)", "reiben",      "reiben",      "reib(e)",     "reib(e)",     
"R)", "reiben",      "reiben",      "gerieben",    "gerieben",    
"Q)", "reißen",      "reißen",      "reiße,  (es)t,  t", "reiße,  (es)t,  t", 
"R)", "reißen",      "reißen",      "riss, rissest", "riss, rissest", 
"R)", "reißen",      "reißen",      "risse",       "risse",       
"R)", "reißen",      "reißen",      "reiß(e)",     "reiß(e)",     
"R)", "reißen",      "reißen",      "gerissen",    "gerissen",    
"Q)", "reiten",      "reiten",      "reite,  est,  et", "reite,  est,  et", 
"R)", "reiten",      "reiten",      "ritt,  (e)st", "ritt,  (e)st", 
"R)", "reiten",      "reiten",      "ritte",       "ritte",       
"R)", "reiten",      "reiten",      "reit(e)",     "reit(e)",     
"R)", "reiten",      "reiten",      "geritten",    "geritten",    
