rem Release\xmlicv.exe ..\mcm\kpn1.xml > xmlicv.lst

rem copy d:\kp\source\tev\xml\Debug\xmlicv.exe d:\kp\source\tev\xml > xmlicv.lst

rem d:\kp\source\tev\xml\xmlicv.exe d:\kp\source\tev\mcm\kpn1.xml >> xmlicv.lst
rem d:\kp\source\tev\xml\xmlicv.exe f:\wrk\kp\source\tev\mcm\kpn1.xml >> xmlicv.lst

rem d:\kp\source\tev\xml\xmlicv.exe f:\wrk\kp\source\tev\mcm\mcm_out\mcm.xml >> xmlicv.lst
rem d:\kp\source\tev\xml\xmlicv.exe f:\wrk\kp\source\tev\mcm\mcm_out\mcmx2.xml >> xmlicv.lst

rem d:\kp\source\tev\xml\xmlicv.exe f:\wrk\kp\source\tev\mcm\mcm_out\mcm1.xml >> xmlicv.lst

f:\kp\source\tev\xml\xmlicv.exe g:\kp\source\tev\lvz\lvz2.xml >> xmlicv.lst
f:\kp\source\tev\xml\xmlicv.exe g:\kp\source\tev\vlz05\vlz2.xml >> xmlicv.lst
f:\kp\source\tev\xml\xmlicv.exe f:\kp\source\tev\lzdsh\kpn2.xml >> xmlicv.lst
