// -----------------------------------------
// kpstlsvr_en.h
// licencijø/rezultatø serverio praneðimai
// liet. kalba
// 

#ifndef kpstlsvr_en_included
#define kpstlsvr_en_included

#if TRUE // ((MsgLang == KpLangNo_p) || (MsgLang == KpLangSel_p) || (MsgLang == KpLangEn_p))

#define KPSTLSVR_MSG_SERVER_STARTED_EN             ((const unsigned char *)"Server started")
#define KPSTLSVR_MSG_PREVIOUS_SESSION_ABANDONED_EN ((const unsigned char *)"previous session abandoned")
#define KPSTLSVR_MSG_INCOMPLETE_REZULTS_WRITTEN_EN ((const unsigned char *)"incomplete results written")
#define KPSTLSVR_MSG_RECEIVED_RESULTS_EN           ((const unsigned char *)"") // " atsiuntë"
#define KPSTLSVR_MSG_INTERMEDIATE_RES_EN           ((const unsigned char *)" intermediate")
#define KPSTLSVR_MSG_FINAL_RES_EN                  ((const unsigned char *)" final")
#define KPSTLSVR_MSG_RESULTS_RECEIVED_EN           ((const unsigned char *)" results received")
#define KPSTLSVR_MSG_REGISTERED_EN                 ((const unsigned char *)" logged in to the test")
#define KPSTLSVR_MSG_SURE_DELETE_MARKED_EN         ((const unsigned char *)"            confirm(\"Are you sure you want to delete all marked records?\");\n")
#define KPSTLSVR_MSG_SURE_DELETE_CONNECTIONS_EN    ((const unsigned char *)"   confirm(\"Are you sure you want to delete all records of connections?\");\n")
#define KPSTLSVR_MSG_ERROR_EN                      ((const unsigned char *)"Error: ")
#define KPSTLSVR_MSG_WARNING_EN                    ((const unsigned char *)"Warning: ")
#define KPSTLSVR_MSG_CLIENT_STATUS_EN              ((const unsigned char *)"Client status")
#define KPSTLSVR_MSG_STATUS_EN                     ((const unsigned char *)" status")
#define KPSTLSVR_MSG_CLIENTS_STATUS_EN             ((const unsigned char *)"Clients\' status")
#define KPSTLSVR_MSG_TAB_STATUS_EN                 ((const unsigned char *)"Status")
#define KPSTLSVR_MSG_TAB_CLIENTS_EN                ((const unsigned char *)"Clients")
#define KPSTLSVR_MSG_TAB_RESULTS_EN                ((const unsigned char *)"Results")
#define KPSTLSVR_MSG_TAB_MESSAGES_EN               ((const unsigned char *)"Messages")
#define KPSTLSVR_MSG_TAB_NETWORK_EN                ((const unsigned char *)"Network")
#define KPSTLSVR_MSG_TAB_ADMINS_EN                 ((const unsigned char *)"Administrators")
#define KPSTLSVR_MSG_ORDER_NO_EN                   ((const unsigned char *)"Order No.")
#define KPSTLSVR_MSG_SESSION_ID_EN                 ((const unsigned char *)"Session ID")
#define KPSTLSVR_MSG_CLIENT_IP_EN                  ((const unsigned char *)"Client IP address")
#define KPSTLSVR_MSG_REST_MIN_EN                   ((const unsigned char *)"Rest min.")
#define KPSTLSVR_MSG_SESSION_ACTIVE_EN             ((const unsigned char *)" session active,")
#define KPSTLSVR_MSG_LOST_CONNECTION_EN            ((const unsigned char *)" lost connection,")
#define KPSTLSVR_MSG_SLOT_FREE_EN                  ((const unsigned char *)" free for logging in.")
#define KPSTLSVR_MSG_REST_MIN__EN                  ((const unsigned char *)"Rest min. ")
#define KPSTLSVR_MSG_LOST_CLI_TIME_EN              ((const unsigned char *)" living time of lost clients")
#define KPSTLSVR_MSG_RESULTS_EN                    ((const unsigned char *)" results")
#define KPSTLSVR_MSG_TEST_RESULTS_EN               ((const unsigned char *)"Test results")
#define KPSTLSVR_MSG_CLASS_PREFIX_EN               ((const unsigned char *)"cl. ")
#define KPSTLSVR_MSG_CLASS_POSTFIX_EN              ((const unsigned char *)"")
#define KPSTLSVR_MSG_RES_FILE_EN                   ((const unsigned char *)"Results are being collected to file ")
#define KPSTLSVR_MSG_BAD_RES_EN                    ((const unsigned char *)" corrupted or unrecognized results;")
#define KPSTLSVR_MSG_BAD_RES_REC_EN                ((const unsigned char *)" corrupted record;") 
#define KPSTLSVR_MSG_TEST_TIMEOUT_EN               ((const unsigned char *)" end of test time.")
#define KPSTLSVR_MSG_MESSAGES__EN                  ((const unsigned char *)" messages")
#define KPSTLSVR_MSG_ERROR_HELP_EN                 ((const unsigned char *)"Report errors and warnings by e-mail to tech@tev.lt")
#define KPSTLSVR_MSG_SESSION_STATUS_EN             ((const unsigned char *)"Session status")
#define KPSTLSVR_MSG_NETWORKS_EN                   ((const unsigned char *)" networks")
#define KPSTLSVR_MSG_ADMINS_EN                     ((const unsigned char *)" administrators")
#define KPSTLSVR_MSG_STATUS__EN                    ((const unsigned char *)" status")
#define KPSTLSVR_MSG_IP_LIST_EN                    ((const unsigned char *)"List of IP addresses, allowed to ")
#define KPSTLSVR_MSG_IP_LIST_SEND_EN               ((const unsigned char *)"send data")
#define KPSTLSVR_MSG_IP_LIST_REGISTER_EN           ((const unsigned char *)"log in")
#define KPSTLSVR_MSG_IP_LIST_ADMIN_EN              ((const unsigned char *)"List of IP addresses, allowed to maintain the server")
#define KPSTLSVR_MSG_CONNECTIONS_LIST_EN           ((const unsigned char *)"List of connections")
#define KPSTLSVR_MSG_SESSION_STARTED_EN            ((const unsigned char *)" session started,")
#define KPSTLSVR_MSG_RESULTS_BEING_SENT_EN         ((const unsigned char *)" results are being received,")
#define KPSTLSVR_MSG_FINAL_RESULTS_SENT_EN         ((const unsigned char *)" final results received,")
#define KPSTLSVR_MSG_SESSION_ABORTED_EN            ((const unsigned char *)" sesion aborted.")
#define KPSTLSVR_MSG_ABORT_PROMPT_EN               ((const unsigned char *)"Press \"Save\" to record all unfinalized results, \"Clear\" to delete all records")
#define KPSTLSVR_MSG_IP_HINT_EN                    ((const unsigned char *)"Use IP address octet 255 to add whole subnet")
#define KPSTLSVR_MSG_PORT_BUSSY_EN                 ((const unsigned char *)"Connection port is bussy, unable to start the server")
#define KPSTLSVR_MSG_MAINTENANCE_STARTED_EN        ((const unsigned char *)"logged in for server maintenance")
#define KPSTLSVR_MSG_MAINTENANCE_REFUSED_EN        ((const unsigned char *)"server maintenance attempt refused")
#define KPSTLSVR_MSG_UNLOGGED_RESULTS_EN           ((const unsigned char *)" received not logged in data")
#define KPSTLSVR_MSG_EXCERCISE_EN                  ((const unsigned char *)"opened question No. ")
#define KPSTLSVR_MSG_EXERCISE_DONE_EN              ((const unsigned char *)"done with question No. ")
#define KPSTLSVR_MSG_CLIENT_LOGGED_IN_EN           ((const unsigned char *)"client logged in")
#define KPSTLSVR_MSG_LOGGING_REFUSED_EN            ((const unsigned char *)"refused client attempt to log in")
#define KPSTLSVR_MSG_CLIENT_LOGGED_OFF_EN          ((const unsigned char *)"client logged off")
#define KPSTLSVR_MSG_RES_LOG_REFUSED_EN            ((const unsigned char *)"refused attempt to log in data transfer")
#define KPSTLSVR_MSG_SERVER_STOPPED_EN             ((const unsigned char *)"Server stopped")
#define KPSTLSVR_MSG_SERVER_ABORTED_EN             ((const unsigned char *)"Server aborted") 
#define KPSTLSVR_MSG_SERVER_ASKED_EN               ((const unsigned char *)"asked for server")
#define KPSTLSVR_MSG_LOG_PROMPT_EN                 ((const unsigned char *)"Detailed messages are being output to file %s")

#endif // #if ((MsgLang == KpLangSel_p) || (MsgLang == KpLangLt_p))

#endif // #ifndef kpstlsvr_en_included
