//---------------------------------------- 
// gen.cpp                                
// programos paleidimo diegimo scenarijus 
// prijungimui prie kpstrpd.exe, Pradzia_[...].exe 
//                                        
#include "envir.h"                        
//                                        
#include "stdlib.h"                       
#include "fstream"                        
#include "windows.h"                      
//                                        
#if Compiler != Watcom                    
using namespace std;                      
#endif                                    
//                                        
#include "kpstdlib.h"                     
//                                        
const unsigned char *GenIssArr[] = {      
(const unsigned char *)";------------------------",
(const unsigned char *)"; gen_flash_start.iss",
(const unsigned char *)"; Installation script",
(const unsigned char *)"; MaTau-5E_mokytojui",
(const unsigned char *)"; \'Matematika Tau-5E mokytojui",
(const unsigned char *)";",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"[Setup]",
(const unsigned char *)"AppPublisher=TEV",
(const unsigned char *)"AppPublisherURL=http://www.tev.lt/",
(const unsigned char *)"AppVersion={code:GetVerStr}",
(const unsigned char *)"VersionInfoCompany=TEV",
(const unsigned char *)"",
(const unsigned char *)"AppName={code:GetProdNameStr}",
(const unsigned char *)"AppVerName={code:GetVerNameStr}",
(const unsigned char *)"",
(const unsigned char *)";ProdVer={code:GetProdVerStr}",
(const unsigned char *)"",
(const unsigned char *)"DefaultDirName={tmp}\\{code:GetProdDirStr}",
(const unsigned char *)"",
(const unsigned char *)"DirExistsWarning=no",
(const unsigned char *)"UsePreviousAppDir=no",
(const unsigned char *)"",
(const unsigned char *)"Uninstallable=no",
(const unsigned char *)"",
(const unsigned char *)"PrivilegesRequired=none",
(const unsigned char *)"",
(const unsigned char *)";OutputDir=Output_flash",
(const unsigned char *)";OutputDir=Output_flash_iso",
(const unsigned char *)";OutputDir=MaTau-5E_mokytojui_v1.11.25_atmintukas\\Output_flash",
(const unsigned char *)";OutputDir=Output_flash_iso\\Matematika Tau-5E mokytojui",
(const unsigned char *)";OutputDir=MIMOK5_v1.11.25_atmintukas\\Output_flash_MaTau5m",
(const unsigned char *)";OutputDir=MIMOK5_v1.11.25_atmintukas\\Output_flash\\{code:GetProdDirStr}",
(const unsigned char *)";OutputDir=MIMOK5_v1.11.25_atmintukas\\Output_flash\\Matematika Tau-5E mokytojui",
(const unsigned char *)";OutputDir=Output_flash_iso\\Matematika Tau-5E mokytojui",
(const unsigned char *)"OutputDir=files_flash",
(const unsigned char *)"",
(const unsigned char *)"OutputBaseFilename=Pradzia_MaTau-5E_mokytojui",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"[Files]",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"[Code]",
(const unsigned char *)"",
(const unsigned char *)"var",
(const unsigned char *)"   bFinishedInstall: Boolean;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetProdVer: String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=\'8010\';",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetProdVerStr(Param: String): String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetProdVer;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetVer: String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=\'v1.11.25\';",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetVerStr(Param: String): String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetVer;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetFirstVer: String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=\'v1.11\';",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function ShouldSkipPage(PageID: Integer): Boolean;",
(const unsigned char *)"begin",
(const unsigned char *)"   Result := True;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetProdNameRaw: String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=\'Matematika Tau-5E mokytojui\';",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetProdName: String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetProdNameRaw;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetProdNameStr(Param: String): String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetProdName;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetVerName: String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetProdName + \' \' + GetVer;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetVerNameStr(Param: String): String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetVerName;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetProdFNameRaw: String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=\'Matematika Tau-5E mokytojui\';",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetProdFName: String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetProdFNameRaw;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetProdFNameStr(Param: String): String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetProdFName;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetProdDir: String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetProdFNameRaw;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetProdDirStr(Param: String): String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetProdDir;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetProdGroup: String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetProdFNameRaw;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetProdGroupStr(Param: String): String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetProdGroup;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetExeFName: String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=\'MaTau5m\';",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetExeFNameStr(Param: String): String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=GetExeFName;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetIconFNameStr(Param: String): String;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=\'matau5.ico\';",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetUpdNum: Integer;",
(const unsigned char *)"begin",
(const unsigned char *)"Result:=1;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function GetAppPath: String;",
(const unsigned char *)"begin",
(const unsigned char *)"// Result:=ExpandConstant(\'{src}\\\' + GetProdDir);",
(const unsigned char *)"   Result:=ExpandConstant(\'{src}\');",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"procedure CurStepChanged(CurStep: TSetupStep);",
(const unsigned char *)"begin",
(const unsigned char *)"   if CurStep = ssPostInstall then",
(const unsigned char *)"      bFinishedInstall := True;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"procedure RunExe;",
(const unsigned char *)"var retv: Integer;",
(const unsigned char *)"begin",
(const unsigned char *)"   if(Not Exec(GetAppPath + \'\\\' + GetExeFName + \'.exe\', \'\', GetAppPath, SW_SHOW, ewNoWait, retv)) then",
(const unsigned char *)"   begin",
(const unsigned char *)"      MsgBox(\'Nepavyko paleisti failo \' + GetExeFName + \'.exe\', mbError, MB_OK);",
(const unsigned char *)"   end;",
(const unsigned char *)"end;",
(const unsigned char *)"",
(const unsigned char *)"",
(const unsigned char *)"function InitializeSetup: Boolean;",
(const unsigned char *)"var retv: Integer;",
(const unsigned char *)"var retw: Boolean;",
(const unsigned char *)"begin",
(const unsigned char *)"",
(const unsigned char *)"   bFinishedInstall := False;",
(const unsigned char *)"",
(const unsigned char *)"      RunExe;",
(const unsigned char *)"",
(const unsigned char *)"      retw:=False; // atsakymas neigiamas, kad nerodytø jokiø tolesniø dialogø, iðkart pasibaigtø",
(const unsigned char *)"",
(const unsigned char *)"Result:=retw;",
(const unsigned char *)"end;",
NULL                                      
};                                        
