xcopy n:\kp\source\Tev\*.* e:\kp\source\Tev /D/S/Y/H/R

xcopy n:\source\*.* f:\source /D/S/Y/H/R

xcopy n:\kp\source\COMMON\*.* f:\kp\source\COMMON /D/S/Y/H/R
xcopy n:\kp\source\kpa\*.* f:\kp\source\kpa /D/S/Y/H/R
xcopy n:\kp\source\kpc\*.* f:\kp\source\kpc /D/S/Y/H/R
xcopy n:\kp\source\kpcdevel\*.* f:\kp\source\kpcdevel /D/S/Y/H/R
xcopy n:\kp\source\kpd\*.* f:\kp\source\kpd /D/S/Y/H/R
xcopy n:\kp\source\kpdard\*.* f:\kp\source\kpdard /D/S/Y/H/R
xcopy n:\kp\source\kpg\*.* f:\kp\source\kpg /D/S/Y/H/R
xcopy n:\kp\source\kphp11\*.* f:\kp\source\kphp11 /D/S/Y/H/R
xcopy n:\kp\source\kpn\*.* f:\kp\source\kpn /D/S/Y/H/R
xcopy n:\kp\source\kpr\*.* f:\kp\source\kpr /D/S/Y/H/R
xcopy n:\kp\source\kprclnt\*.* f:\kp\source\kprclnt /D/S/Y/H/R
xcopy n:\kp\source\kprgdl\*.* f:\kp\source\kprgdl /D/S/Y/H/R
xcopy n:\kp\source\kprsrv\*.* f:\kp\source\kprsrv /D/S/Y/H/R
xcopy n:\kp\source\kps\*.* f:\kp\source\kps /D/S/Y/H/R
xcopy n:\kp\source\kpshid\*.* f:\kp\source\kpshid /D/S/Y/H/R
xcopy n:\kp\source\kpsinst\*.* f:\kp\source\kpsinst /D/S/Y/H/R
xcopy n:\kp\source\kpsmsg1\*.* f:\kp\source\kpsmsg1 /D/S/Y/H/R
xcopy n:\kp\source\kpspti\*.* f:\kp\source\kpspti /D/S/Y/H/R
xcopy n:\kp\source\kpsptiw\*.* f:\kp\source\kpsptiw /D/S/Y/H/R
xcopy n:\kp\source\kpstart\*.* f:\kp\source\kpstart /D/S/Y/H/R
xcopy n:\kp\source\kpswct\*.* f:\kp\source\kpswct /D/S/Y/H/R
xcopy n:\kp\source\kpt\*.* f:\kp\source\kpt /D/S/Y/H/R
xcopy n:\kp\source\mindep\*.* f:\kp\source\mindep /D/S/Y/H/R
xcopy n:\kp\source\mindep.fotki\*.* f:\kp\source\mindep.fotki /D/S/Y/H/R
xcopy n:\kp\source\mindep.wrk\*.* f:\kp\source\mindep.wrk /D/S/Y/H/R
xcopy n:\kp\source\testkey\*.* f:\kp\source\testkey /D/S/Y/H/R
xcopy n:\kp\source\testkey0\*.* f:\kp\source\testkey0 /D/S/Y/H/R
xcopy n:\kp\source\TEV_LEID\*.* f:\kp\source\TEV_LEID /D/S/Y/H/R
xcopy n:\kp\source\TEV_PDF\*.* f:\kp\source\TEV_PDF /D/S/Y/H/R
xcopy n:\kp\source\wxWidgets\*.* f:\kp\source\wxWidgets /D/S/Y/H/R
xcopy n:\kp\source\wxWidgetsDemo\*.* f:\kp\source\wxWidgetsDemo /D/S/Y/H/R
