// ---------------------------
// lzdsh resources, events and id's

// --------------------------------
#ifndef lzdshn_included
#error lzdshn.h not included
#endif

#ifndef IBSH_SKIN
#error IBSH_SKIN undefined
#endif

// --------------------------
// #define LZDSH_IDI_BOOK_ICON      200 // 150
#define LZDSH_IDI_LED_ICON          KP_IDI_MAIN_ICON // 200 // 150

#if IBSH_SKIN == IBSH_SKIN_STANDART
#define LZDSH_IDI_ZOOM_SEL_ICON     201 // 151   // zoom + icon
#define LZDSH_IDI_ZOOM_ICON         202 // 152   // zoom - icon
#define LZDSH_IDI_WIDE_ICON         203 // 153   // narrow mode icon
#define LZDSH_IDI_WIDE_SEL_ICON     204 // 154   // wide mode icon
#define LZDSH_IDI_ACC_SEL_ICON      205 // 155
#define LZDSH_IDI_ACC_ICON          206 // 156
#define LZDSH_IDI_SEARCH_ICON       207 // 157
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_ZOOM_SEL_BITMAP   208 // 151   // zoom + icon
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_LIGHT)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_ZOOM_BITMAP       209 // 152   // zoom - icon
#define LZDSH_IDI_WIDE_BITMAP       210 // 153   // narrow mode icon
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_WIDE_SEL_BITMAP   211 // 154   // wide mode icon
#define LZDSH_IDI_ACC_SEL_BITMAP    212 // 155
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_LIGHT)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_ACC_BITMAP        213 // 156
#define LZDSH_IDI_SEARCH_BITMAP     214 // 157
#endif

#define LZDSH_IDI_MAIN_BITMAP       215 // 158
#define LZDSH_IDI_SEARCH_ROT_BITMAP 216 // 159
#define LZDSH_IDI_HIST_BITMAP       217 // 160

#if IBSH_SKIN == IBSH_SKIN_STANDART
#define LZDSH_IDI_MAIN_MASK_BITMAP  218 // 161
#define LZDSH_IDI_SEARCH_ROT_MASK_BITMAP 219 // 162
#define LZDSH_IDI_HIST_MASK_BITMAP  220 // 163
#endif

// #if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_LIGHT)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_BMP_BCKGRND       KP_IDI_BMP_BCKGRND // 221 // 164
// #endif

#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_ZOOM_LIGHT_BITMAP 222 // 165
#define LZDSH_IDI_WIDE_LIGHT_BITMAP 223 // 166
#define LZDSH_IDI_ACC_LIGHT_BITMAP  224 // 167
#define LZDSH_IDI_SEARCH_LIGHT_BITMAP  225 // 168
#endif

#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_SEARCH_SEL_BITMAP    226 // 169
#endif

#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_MAIN_LIGHT_BITMAP    227 // 170
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_LIGHT)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_MAIN_SEL_BITMAP      228 // 171
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_SEARCH_ROT_LIGHT_BITMAP 229 // 172
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_LIGHT)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_SEARCH_ROT_SEL_BITMAP   230 // 173
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_HIST_LIGHT_BITMAP    231 // 174
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_LIGHT)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_HIST_SEL_BITMAP      232 // 175
#endif

#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_LIGHT)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_MINIMIZE_BITMAP      KP_IDI_MINIMIZE_BITMAP // 233 // 176
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_MINIMIZE_LIGHT_BITMAP   KP_IDI_MINIMIZE_LIGHT_BITMAP // 234 // 177
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_MINIMIZE_SEL_BITMAP     KP_IDI_MINIMIZE_SEL_BITMAP // 235 // 178
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_LIGHT)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_EXIT_BITMAP          KP_IDI_EXIT_BITMAP // 236 // 179
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_EXIT_LIGHT_BITMAP    KP_IDI_EXIT_LIGHT_BITMAP // 237 // 180
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_EXIT_SEL_BITMAP      KP_IDI_EXIT_SEL_BITMAP // 238 // 181
#endif

#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_LIGHT)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_BMP_LOGO             239 // 182
#define LZDSH_IDI_BMP_FMENU            240 // 183
#endif

#if IBSH_SKIN == IBSH_SKIN_STANDART
#define LZDSH_IDI_BACK_ICON            241 // 184
#define LZDSH_IDI_FORWARD_ICON         242 // 185
#endif
#if (IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON)||(IBSH_SKIN == IBSH_SKIN_LZDSH_MAHAGON_3D)
#define LZDSH_IDI_BACK_BITMAP          243 // 184
#define LZDSH_IDI_FORWARD_BITMAP       244 // 185

#define LZDSH_IDI_BACK_LIGHT_BITMAP    245 // 186
#define LZDSH_IDI_BACK_SEL_BITMAP      246 // 187
#define LZDSH_IDI_FORWARD_LIGHT_BITMAP 247 // 188
#define LZDSH_IDI_FORWARD_SEL_BITMAP   248 // 189
#endif

// -----------------------------------------------
// m_hDialogWindow id
#define LZDE_ID_DIALOG               249 // 201

// m_pNodList id
#define LZDE_ID_NODLIST              250 // 202
